[package]
name = "rocket-rust-jobs"
version = "0.1.0"
edition = "2021"

[dependencies]
advisory-lock = "0.3.0"
rocket = "0.5.1"
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
tempfile = "3.11.0"
